### ISSUE TITLE
Initial value not recovered in editor mode

### ISSUE THREAD

**Issue by boscohyun** [brunomikoski/Animation-Sequencer#12]
When playing `AnimationSequencerController` in Editor mode, the result value of `AnimationSteps` with `Duration` of `0` is fixed, so it is not restored to the initial value after playback is finished.

### Expacted

before
<img src="https://user-images.githubusercontent.com/6128868/122646247-29e37880-d159-11eb-996d-91ad81f8289c.png" width="50%">

after
<img src="https://user-images.githubusercontent.com/6128868/122646815-18e83680-d15c-11eb-9816-0c39457ace64.png" width="50%">

### Unexpacted

before
<img src="https://user-images.githubusercontent.com/6128868/122646262-3798fe00-d159-11eb-804b-7acc6362a4e2.png" width="50%">

after
<img src="https://user-images.githubusercontent.com/6128868/122646269-42539300-d159-11eb-8478-5130c3989621.png" width="50%">

**Comment by brunomikoski** [comment]
Fixed on: https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.1.6
