### ISSUE TITLE
Doesn't Compile in Unity 2018.4

### ISSUE THREAD

**Issue by nindim** [brunomikoski/Animation-Sequencer#14]
Hi,

I tried to import this in Unity 2018.4.23 but it is using SerializedReference which to my knowledge was only added in 2019.3.

Thanks,

Niall

**Comment by brunomikoski** [comment]
Yeah, sadly I built based on the SerializedRefernce, which makes retro compatibility impossible, and ATM I don't have plans to implement one alternative
