### ISSUE TITLE
[REQUEST] Various Features

### ISSUE THREAD

**Issue by nindim** [brunomikoski/Animation-Sequencer#16]
Hi,

Before finding this Plugin I actually started using https://github.com/Luomu/UIAnimSequencer and ended up extending & changing it quite heavily to fit our needs (the first thing I did was move it to DOTween for instance).

It looks as though your version of this tool is far better organised and more easily extensible so at some point I would like to switch my project to this plugin if it can gain feature parity.

**DOTween Sequences**
Looking at the source, you don't seem to be using DOTween's Sequence object. This surprised me as it maps 1:1 with SpaceApe's implementation and under the hood I think they are likely using it. It would remove a lot of the need for manually moving through steps and actions as you just set it all up on the Sequence up front, it then handles all the scheduling, delays etc. You then only need to worry about playback of the Sequence from that point onward and you can start doing interesting things like playing the Sequence backwards and scrubbing to arbitrary points in time across the entire Sequence.

**Preview Enhancements**
![image](https://user-images.githubusercontent.com/7597004/127737438-1d0961da-11fc-437c-913c-85cd125073e2.png)
My current implementation supports:
- Simulated frame step (forwards and backwards).
- Play/Pause.
- Stop - This is to end the preview when you have paused or scrubbed.
- Speed slider to control the preview speed, this is super useful for analysing glitches/pops and the like.
- Progress slider - This allows you to scrub the entire Sequence forwards and backwards at will.

While the preview is active the user is told not to save the scene, the UIAnimSequence component is also prevented from being edited:
![image](https://user-images.githubusercontent.com/7597004/127737606-778f03c3-26f8-4e25-afc1-2acb073e7a94.png)

**Unscaled Time**
Tick box that decides whether the Sequence plays back using scaled or unscaled time. Essential for UI animation when the rest of the game is paused.

**Play Backwards**
This is very useful as sometimes you just want the intro and outro of an object to be the same (but reversed). Otherwise you need to recreate the same animation backwards in a separate Sequencer.

**Disable After...**
![image](https://user-images.githubusercontent.com/7597004/127737757-06be9be9-56b7-488f-b4ac-7ad6d7816b35.png)
This automatically disables the object after playback completes. It's essentially like having an "Invoke Callback Step" that can be moved around depending on the playback direction. When adding backwards playback this is fairly essential.

**Start/Finish Callbacks**
![image](https://user-images.githubusercontent.com/7597004/127737975-18734b10-b835-4f03-b349-a592e20b08ea.png)
As with "Disable After..." these are needed if backward playback is supported.

**Default Values**
I think it would be very useful to expose various defaults in a ScriptableObject or the like so all of the defaults can be tweaked per project.

For the ease I have set this to "In Out Quad" as it most close matches the Easy Ease used in various software such as After Effects It also seems to be the one most motion graphics artists start with.

**Wait for...**
My game has the concept of a FadeManager that fades the screen up and down, I usually do not want my UI animations to start during the fade. As I have control of the source for my Sequencer I just added a link to this system.

![image](https://user-images.githubusercontent.com/7597004/127737867-ff949f06-3b9d-411d-b554-42bed30b8d80.png)

For a more generic system like yours perhaps there is a way to register some prerequisite conditions before the animation can start... I'm not sure of the most flexible way to handle this though if I'm honest.

Thanks a lot for open sourcing this project anyway, it's very, very interesting even as it is but the above features would really make it a no brainer for us to use!

All the best,

Niall

**Comment by brunomikoski** [comment]
Thanks for all the information! Indeed a lot of cool ideas and things to be taking into consideration! 

I decided to not made based on DOTween sequences, because I want the system to be a little bit more generic and expandable, for instance, you could make it work with any other tween engine, or in some of my cases, I used to create just sequence of other tweens not tween related, so they don't need to be using the DOTween. 

But yeah, maybe just embracing DOTween would be better at this point! 

I'm kinda busy at work ATM, but I will investigate all the suggestions and make a plan to implement them, but please feel free to open Pull Requests with changes! I will love to get some support from other developers on this!

**Comment by brunomikoski** [comment]
Hey @nindim I found some time this weekend and actually implement a lot of your suggestions on the v0.2.0! Let me know what you think :)

**Comment by nindim** [comment]
Hey @brunomikoski,

Amazing! I will give it a go and let you know how I get on.

All the best.
