### ISSUE TITLE
DOTween Install

### ISSUE THREAD

**Issue by andybak** [brunomikoski/Animation-Sequencer#18]
I installed the OpenUPM version of DOTween: https://openupm.com/packages/com.demigiant.dotween/ and it doesn't appear to be compatible.

It might be worth clarifying how you recommend installing DOTween. Also - if the order is important then those steps would be useful in the "Installation" section of the readme. I usually skip reading everything else and start there but the reference to DOTween is further up the page.

**Comment by brunomikoski** [comment]
Yeah I definitely need to work on that part, but I'm not sure about supporting the unofficial DOTween package, it's quite outdated and I want to allow people with DOTween Pro from the asset store to import the version that they want. 

But I will improve the installation part on the readme and maybe create some define tags so you don't have compilation errors while updating DOTween or downloading from somewhere else!

**Comment by brunomikoski** [comment]
Implemented on the [release](https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.2.8)
