### ISSUE TITLE
Rotate to euler angles can not loop ?

### ISSUE THREAD

**Issue by Bian-Sh** [brunomikoski/Animation-Sequencer#19]
![image](https://user-images.githubusercontent.com/24520547/128681643-28750b76-5a58-482c-88d4-c220406c0c1d.png)

If the setting is correct there is a problem, that is loop function invalide.

**Comment by Bian-Sh** [comment]
![image](https://user-images.githubusercontent.com/24520547/128796592-de12f80a-70dc-4710-8084-aa856c7ac9f2.png)
tweens added to a Sequence can't have infinite loops (but the root Sequence can).

**Comment by brunomikoski** [comment]
> ![image](https://user-images.githubusercontent.com/24520547/128796592-de12f80a-70dc-4710-8084-aa856c7ac9f2.png)
> tweens added to a Sequence can't have infinite loops (but the root Sequence can).

Thanks for the clarification! I want not sure about that as well!?
I think I can add the loops setting for the animation controller as a whole, that would give you an option of how to do that right?

**Comment by Bian-Sh** [comment]
maybe, and we can have a test later.

**Comment by brunomikoski** [comment]
Give a try to the 0.2.1 release:
https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.2.1

**Comment by Bian-Sh** [comment]
![image](https://user-images.githubusercontent.com/24520547/128895771-c95c7612-37da-4775-84b7-ba6ba4e3126e.png)

Maybe both of these two param should be hide  if sequence is in infinite loop state.

**Comment by Bian-Sh** [comment]
Could you pls give a choice to user， if it didnt want a animation step insert/append to a sequence.
The infinite loop does not behave as I expected : I need steps run in parallel but not one by one (see the gif pic).
Flowtype can append a item named "independence" maybe .
![aninseq](https://user-images.githubusercontent.com/24520547/129025012-d64a977a-784b-46f1-add5-46de79e30c66.gif)

**Comment by brunomikoski** [comment]
I believe you could just use the Play Sequence Action to trigger 2 different Animation Sequencer with your settings right? 


But in this case looks like you are looking for the step 1 and 2 to use the Join flow type, both would start at the same time, right?

**Comment by Bian-Sh** [comment]
yes ,yes 
and I found that neither apend nor join can make them start at the same time.
