### ISSUE TITLE
Could you please include sample project like in the gif

### ISSUE THREAD

**Issue by takaaptech** [brunomikoski/Animation-Sequencer#2]
Hi @brunomikoski 
Your plugin looks awesome!
Please add the sample project so we can learn from it
Thank you so much for sharing with us!

**Comment by brunomikoski** [comment]
Hey @takaaptech , sadly I cannot since this is a paid asset from the asset store, check it out here: https://assetstore.unity.com/packages/2d/gui/gui-pro-kit-casual-game-176695


I have plans to implement some demo soon with some open source files.

**Comment by takaaptech** [comment]
@brunomikoski I see, let grab some open-source art file on the assets store and make some demo!
Thank you!
