### ISSUE TITLE
Update FAQ for creating Custom action and DOTween extensions.

### ISSUE THREAD

**Issue by foxgunner** [brunomikoski/Animation-Sequencer#21]
Hi,
 
Please update the FAQ for creating custom action and DOTween extensions. I managed to get them working by looking at your implementation. But it would be great to get some official help.

**Comment by brunomikoski** [comment]
Its the second item on the FAQ:

https://github.com/brunomikoski/Animation-Sequencer#faq

Is not clear enough?

**Comment by foxgunner** [comment]
> Its the second item on the FAQ:
> 
> https://github.com/brunomikoski/Animation-Sequencer#faq
> 
> Is not clear enough?

I meant to say that the FAQs are for v0.1.6 version. You will need to update it for 0.2.0 and above. Thanks :)

**Comment by brunomikoski** [comment]
Fixed!
https://github.com/brunomikoski/Animation-Sequencer/pull/22
