### ISSUE TITLE
Animation Sequencer does not see DOTween

### ISSUE THREAD

**Issue by eonyanov** [brunomikoski/Animation-Sequencer#23]
After install I get errors in Editor:
Library\PackageCache\com.brunomikoski.animationsequencer@0.2.2\Scripts\Runtime\Core\DOTweenActions\AnchoredPositionMoveDOTweenActionBase.cs(32,89): error CS1061: 'RectTransform' does not contain a definition for 'DOAnchorPos' and no accessible extension method 'DOAnchorPos' accepting a first argument of type 'RectTransform' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.brunomikoski.animationsequencer@0.2.2\Scripts\Runtime\Core\DOTweenActions\ColorGraphicDOTWeen.cs(33,68): error CS1929: 'Graphic' does not contain a definition for 'DOColor' and the best extension method overload 'ShortcutExtensions.DOColor(Camera, Color, float)' requires a receiver of type 'Camera'

Library\PackageCache\com.brunomikoski.animationsequencer@0.2.2\Scripts\Runtime\Core\DOTweenActions\FadeCanvasGroupDOTweenAction.cs(33,67): error CS1929: 'CanvasGroup' does not contain a definition for 'DOFade' and the best extension method overload 'ShortcutExtensions.DOFade(Material, float, float)' requires a receiver of type 'Material'

Library\PackageCache\com.brunomikoski.animationsequencer@0.2.2\Scripts\Runtime\Core\DOTweenActions\FadeGraphicDOTweenAction.cs(33,68): error CS1929: 'Graphic' does not contain a definition for 'DOFade' and the best extension method overload 'ShortcutExtensions.DOFade(Material, float, float)' requires a receiver of type 'Material'

Library\PackageCache\com.brunomikoski.animationsequencer@0.2.2\Scripts\Runtime\Core\DOTweenActions\FillImageDOTweenAction.cs(33,67): error CS1061: 'Image' does not contain a definition for 'DOFillAmount' and no accessible extension method 'DOFillAmount' accepting a first argument of type 'Image' could be found (are you missing a using directive or an assembly reference?)

I went to Packages>Animation Sequencer>Scripts>Runtime. 
Checked BrunoMikoski.AnimationSequencer.asmdef
and there was no link to DOTween.Modules assembly

![image](https://user-images.githubusercontent.com/6646489/129753030-e259280a-65b7-4f7b-8b00-ecd6833845e2.png)

**Comment by eonyanov** [comment]
I created ASMDEFs from DOTween Utility Panel and got new error:

Library\PackageCache\com.brunomikoski.animationsequencer@0.2.2\Scripts\Editor\Core\AnimationSequencerControllerCustomEditor.cs(113,38): error CS0117: 'DOTweenEditorPreview' does not contain a definition for 'isPreviewing'

**Comment by eonyanov** [comment]
Update Dotween and DOtweenPro for last version, issue is gone :)

**Comment by brunomikoski** [comment]
Glad that you figured out :)
