### ISSUE TITLE
FlowType Join works as Append

### ISSUE THREAD

**Issue by eonyanov** [brunomikoski/Animation-Sequencer#24]
I added few steps in sequence with FlowType Join. All steps have action Scale to Size. 
When I hitted preview Play, steps animated one after another, not simultaneously.
And I also did not find a way to add a time interval to the sequence (like sequence.AppendInterval(5f))

**Comment by brunomikoski** [comment]
Fixed here:
https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.2.3

It's a weird issue related to delays and multiple chained sequences

Let me know if its working properly

**Comment by eonyanov** [comment]
Now it working properly, but the sequence callback seems to have disappeared.
My sequence setup below:
![image](https://user-images.githubusercontent.com/6646489/129853961-fd765bfd-cfb1-4e31-9a0a-7ae959aa2b7a.png)

AnimationSequencer_hide not called.

**Comment by brunomikoski** [comment]
Please git it a try to the this release  https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.2.4
