### ISSUE TITLE
[0.2.4] Preview feature is broken

### ISSUE THREAD

**Issue by boscohyun** [brunomikoski/Animation-Sequencer#26]
Unity: 2020.3.4f1
Tested package version: 0.2.4

I already used this package version 0.1.6 and I upgraded to 0.2.4 lately.
The preview feature of version 0.2.4 is broken.
The origin value is not restored when the preview ends.

**Comment by brunomikoski** [comment]
I just tested with unity 2020.3.17f and everything is working fine, could you explain a little bit better what you mean by broken? 
**Unity:** 2020.3.17f1
**AnimationPackage:** v0.2.4
**DOTween:** v1.2.632 [Release]

**Comment by studentutu** [comment]
Same issue : with 0.2.4 - I'm using older version of the DOTween - and it does not have DotweenEditorPreview.isPreviewing field/property.
![image](https://user-images.githubusercontent.com/18601652/133231986-0ed3df2f-59e9-450e-a903-4a58df62ce19.png)

I'm fixing it locally with a reflexion call for now...
@brunomikoski  please take a look

**Comment by studentutu** [comment]
@brunomikoski  also, please update all of the Assembly definition to not use GUID but prefer to use name of the assembly. This way there will be no import error when using this with older versions of Unity or when re-importing project with large amount of files (duplicate GUID s may be encountered )

**Comment by brunomikoski** [comment]
> Same issue : with 0.2.4 - I'm using older version of the DOTween - and it does not have DotweenEditorPreview.isPreviewing field/property.
> ![image](https://user-images.githubusercontent.com/18601652/133231986-0ed3df2f-59e9-450e-a903-4a58df62ce19.png)
> 
> I'm fixing it locally with a reflexion call for now...
> @brunomikoski please take a look

Sadly I need to use the new updated version of DOTween to fix some issues with sequences playing on the editor, can't you upgrade DOTween on your project?

**Comment by brunomikoski** [comment]
> @brunomikoski also, please update all of the Assembly definition to not use GUID but prefer to use name of the assembly. This way there will be no import error when using this with older versions of Unity or when re-importing project with large amount of files (duplicate GUID s may be encountered )

I will upgrade on the next release, but from what I saw the only one using GUID is the Editor right? That's embedded inside the package so should not be a problem

**Comment by brunomikoski** [comment]
Done.
