### ISSUE TITLE
'DOTweenEditorPreview' does not contain a definition for 'isPreviewing'

### ISSUE THREAD

**Issue by nindim** [brunomikoski/Animation-Sequencer#27]
Hey @brunomikoski ,

Just trying out version 0.2.4 with DOTween 1.2.632 and getting this:

Assets\Animation-Sequencer\Scripts\Editor\Core\AnimationSequencerControllerCustomEditor.cs(113,38): error CS0117: 'DOTweenEditorPreview' does not contain a definition for 'isPreviewing'

![image](https://user-images.githubusercontent.com/7597004/131496035-0064306c-f108-4565-a271-df814d52386a.png)

Did you manually edit DOTween to expose this?

All the best.

**Comment by brunomikoski** [comment]
I just tested both 0.24 of the sequencer and DOTween 1.2.632  and both are working here, are you sure you created the asmdef files from the DOTween Setup Panel?

**Comment by nindim** [comment]
Hey @brunomikoski ,

Yeah, I definitely did that as I was getting other errors prior to that.

Using Rider to peek into the DOTween code, only _isPrviewing exists and it is Private:

![image](https://user-images.githubusercontent.com/7597004/131531753-1359e928-a322-4156-8b69-80b480b7933a.png)

To repro:

1. Create new Unity 2019.4.29 3D Project
2. Import Animation Sequencer 0.2.4
3. Import the free DOTween from Asset Store - "DOTween (HOTween v2)" - https://assetstore.unity.com/packages/tools/animation/dotween-hotween-v2-27676
4. Setup DOTween with all tickboxes
5. Create the .asmdef files.

Repro Project: https://drive.google.com/file/d/1-M51qlSm1JNDETA4n138bXlZ16QyHtKG/view?usp=sharing

All the best.

**Comment by brunomikoski** [comment]
Looks like DOTween version on Asset Store it outdated:
![image](https://user-images.githubusercontent.com/600419/131634519-e84e6adf-46cd-43ef-86d0-c9212076b66d.png)

Install the version v1.2.632 from their website:
http://dotween.demigiant.com/download.php

**Comment by nindim** [comment]
That's really weird, it does list as the same version in the Asset Store:

![Screenshot_20210901-090201](https://user-images.githubusercontent.com/7597004/131635224-b3b3d4b3-6075-4d3d-9eb5-dfa5f585cf29.jpg)
 
I'll give the version you linked a shot.

Thanks!

**Comment by nindim** [comment]
The direct download from the DOTween site has resolved this, thank you.

**Comment by Demigiant** [comment]
Holy cow I'm so sorry, also for not seeing this sooner! I just checked and the Asset Store reports the right package uploaded so I don't understand what happened, but I'll re-upload a newer version within the week (which also has a few nicer additions) 👀

**Comment by Demigiant** [comment]
Uhm, but wait, I just tried downloading DOTween from the Asset Store, using Unity 2019, and I got the right 1.2.632 version. Could you tell me the exact process you followed to download? Maybe there's a specific Asset Store procedure that for some mysterious reason downloads an older version

**Comment by brunomikoski** [comment]
Maybe was some caching issue? But I noticed this a couple of times with this past release, that said one version on the asset store, but when you download it, was actually a older version

**Comment by nindim** [comment]
The weird thing is that DOTween itself was telling me I had the newest version in the Utility Panel but it was missing the IsPreviewing functionality.

I wonder if I somehow got a frankenbuild.and that is how I was missing the required functionality... .That said, I'm 99.9% sure I imported it fresh into a new project!
