### ISSUE TITLE
Play sequence backwards.

### ISSUE THREAD

**Issue by BruceKristelijn** [brunomikoski/Animation-Sequencer#32]
What's the best way to revert the sequence in code? I currently have a pretty weird setup:
`        public override void StartTransition(int direction, Callback callback, RectTransform targetTransform)
        {
            this.direction = direction;
            sequencerController = targetTransform.GetComponent<AnimationSequencerController>();

            targetTransform.gameObject.SetActive(true);
            if (direction == 1)
            {
                SetForwardBackward(0);
                sequencerController.GenerateSequence();
                sequencerController.Play();
                sequencerController.PlayingSequence.SetAutoKill(false);
            }
            else
            {
                SetForwardBackward(1);
                sequencerController.Kill();
                sequencerController.Play();
                sequencerController.PlayingSequence.Goto(1 * sequencerController.PlayingSequence.Duration());
                sequencerController.PlayingSequence.Play();
            }
        }

        private void SetForwardBackward(int enumint)
        {
            var enumtype = typeof(AnimationSequencerController).Assembly.GetType("BrunoMikoski.AnimationSequencer.AnimationSequencerController+PlayType");
            var newenum = Enum.ToObject(enumtype, enumint);
            var prop = typeof(AnimationSequencerController).GetField("playType", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            prop.SetValue(sequencerController, newenum);
        }`

It works but there's probably a better way isn't there?

**Comment by brunomikoski** [comment]
You could just change the direction on the editor right? 

![image](https://user-images.githubusercontent.com/600419/144515280-1efc2d77-0619-4c66-9bee-8aeab2d058ed.png)

I'm exposing this to be called by code as well on the next version

**Comment by brunomikoski** [comment]
Implemented on the [release](https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.2.8)
