### ISSUE TITLE
Rewind and PlayBackward not working

### ISSUE THREAD

**Issue by sadegh-askari** [brunomikoski/Animation-Sequencer#34]
Hi,
I use this package for a long time and its work correctly in my case.
Recently i upgrade from my old version 0.2.4 to 0.2.7 and even 0.2.8 and in new release Rewind function or PlayBackward not working at all.

**Comment by brunomikoski** [comment]
I will take a look!

**Comment by brunomikoski** [comment]
Do you mean in playtime? Or on editor time?

**Comment by sadegh-askari** [comment]
> Do you mean in playtime? Or on editor time?

Playtime

**Comment by sadegh-askari** [comment]
I test it again and found that when i upgrade to 0.2.6 and above versions Rewind function not works and if i downgrade to 0.2.4 it works again

**Comment by brunomikoski** [comment]
> I test it again and found that when i upgrade to 0.2.6 and above versions Rewind function not works and if i downgrade to 0.2.4 it works again

I will double-check and compare this weekend and get back to you.

**Comment by brunomikoski** [comment]
It should be fixed on the https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.3.0
