### ISSUE TITLE
Join behaves as Append

### ISSUE THREAD

**Issue by JohnDesley** [brunomikoski/Animation-Sequencer#37]
Hello,

You recently changed, in `ee79e77f3ce49d1ac14475b02c88f36210388ba6`,  the `SetDelay` to `AppendInterval`. 
I understand what you were trying to achieve with the fix, but there is a bug.

For example:
- `Append { duration: 1, delay: 2 }`
- `Join {duration: 1, delay: 0}`

When calling the `Join` method the `lastTweenInsertTime`will be `3` (duration + delay of the append).
This means that the `Join` will start *after* the `Append` instead of at the same time (+ delay).
Due to this the `Join` behaves as an `Append`.

For the time being I will locally revert this commit in my fork until this problem is solved.

**Comment by brunomikoski** [comment]
Could you try the last release @JohnDesley , I believe this issue has been fixed on [v0.3.3](https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.3.3)

**Comment by JohnDesley** [comment]
Seems to be working again! Thanks for the quick fix 👍
