### ISSUE TITLE
Target not updating

### ISSUE THREAD

**Issue by JohnDesley** [brunomikoski/Animation-Sequencer#38]
Hello,

In `AnchoredPositionMoveDOTweenActionBase.GenerateTween_Internal` there is a null check on a rectTransform. Initially this is valid, but this is problematic when refreshing the `target`.

Simply by removing the null check the rectTransform will be up to date. Casting isn't that expensive so for runtime this should've no impact.

**Comment by brunomikoski** [comment]
I believe this also has been fixed, or you are using a really old version where the SetTarget was available? Could you confirm what version are you using it? 

And give it a try on the latest one.

**Comment by JohnDesley** [comment]
Seems to be working again! Thanks for the quick fix 👍
