### ISSUE TITLE
Animation Steps changes at runtime

### ISSUE THREAD

**Issue by gollumino** [brunomikoski/Animation-Sequencer#42]
Is it possibile to change the values of steps and actions through code at runtime?

**Comment by brunomikoski** [comment]
It used to be in the past but was quite annoying to do, I'm planning on allowing some sort of ID for getting and editing steps, but it's not available yet.

**Comment by brunomikoski** [comment]
There's a experimental working version here: https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.3.5

Let me know if that works for you
