### ISSUE TITLE
Does not support 2021.3.0f1 There will be some errors

### ISSUE THREAD

**Issue by BadZhang** [brunomikoski/Animation-Sequencer#45]
![屏幕截图 2022-04-23 204226](https://user-images.githubusercontent.com/10047133/164894994-e58600b4-4f52-486a-bce3-3fabf8902523.png)

**Comment by brunomikoski** [comment]
I will take a closer look to it, now that 2021 will be LTS

**Comment by brunomikoski** [comment]
I'm testing on unity 2021.3.2f1 and everything is working as expected, what version of the unity and the project you are using?

**Comment by BadZhang** [comment]
Unity 2021.3.0+


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "brunomikoski/Animation-Sequencer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月12日(星期四) 凌晨5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [brunomikoski/Animation-Sequencer] Does not support 2021.3.0f1 There will be some errors (Issue #45)





 
I'm testing on unity 2021.3.2f1 and everything is working as expected, what version of the unity and the project you are using?

**Comment by brunomikoski** [comment]
Should work properly with https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.3.6
