### ISSUE TITLE
Export a unity package breaks the actions in the animation steps

### ISSUE THREAD

**Issue by deviwinnow** [brunomikoski/Animation-Sequencer#46]
If I try to export a package with an Animation Sequencer Controller and open it in another unity project, I can see the steps, but all the actions are empty.
Is there anything I can do?
Thanks

**Comment by brunomikoski** [comment]
I need to investigate this further, not sure if this is something easy to do to be honest.

**Comment by deviwinnow** [comment]
Thank you.
In the meantime do you have any suggestion to be able to copy an animation sequencer controller from a project to another?

**Comment by brunomikoski** [comment]
> Thank you. In the meantime do you have any suggestion to be able to copy an animation sequencer controller from a project to another?

Sadly I don't think there's an easy of doing this ATM, since most of the references are inside the package.

I'm have plans to implement a way of exporting the animation as a shareable file somehow, but its really far from production ready.
