### ISSUE TITLE
OnFinishedEvent with a loop is fired at each tick

### ISSUE THREAD

**Issue by burakomer** [brunomikoski/Animation-Sequencer#51]
When setting a finite loop, the OnFinishedEvent is fired at each tick. I think it should be registered as an OnComplete callback rather than AppendCallback callback.

**Comment by brunomikoski** [comment]
Sorry that it took me so long to be able to take a look at this, but actually using the `OnComplete` for this causes other problems when rewinding tween as well. 
I will investigate this further to try to find a better solution

**Comment by burakomer** [comment]
Thanks! For the time being, my solution was to set the loop under the step, then add a callback on the next step. This works for simple tweens.

**Comment by brunomikoski** [comment]
I'm glad you figure out a better way of handling it!  I will close the issue for now! :D
