### ISSUE TITLE
Package not compiling with 2020.3

### ISSUE THREAD

**Issue by aixaCode** [brunomikoski/Animation-Sequencer#53]
Version `0.3.9` is not compiling on Unity `2020.3`
Version 0.3.8 is working properly.
Tested with Unity version `2020.3.35f1`

Errors:
`Library\PackageCache\com.brunomikoski.animationsequencer@0.3.9\Scripts\Editor\Core\AnimationSequencerControllerCustomEditor.cs(50,13): error CS0234: The type or namespace name 'PrefabStage' does not exist in the namespace 'UnityEditor.SceneManagement' (are you missing an assembly reference?)`

`Library\PackageCache\com.brunomikoski.animationsequencer@0.3.9\Scripts\Editor\Core\AnimationSequencerControllerCustomEditor.cs(68,13): error CS0234: The type or namespace name 'PrefabStage' does not exist in the namespace 'UnityEditor.SceneManagement' (are you missing an assembly reference?)`

**Comment by brunomikoski** [comment]
Fixed here: https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.4.0
