### ISSUE TITLE
Steps foldout closes when playing animation

### ISSUE THREAD

**Issue by timbo-tj** [brunomikoski/Animation-Sequencer#55]
Hey there! Firstly, a fantastic repository! Saving me a ton of time and working flawlessly.

One thing that I noticed is that when I preview the animation in the editor it collapses the Steps foldout. It's a bit tedious.

I make a small tweak to a step, I preview it, need to make another small adjustment but I have to reopen the steps foldout. It really hurts iteration speed.

I was wondering if there was a way to have the steps foldout remain open?

**Comment by brunomikoski** [comment]
Hey @timbo-tj , I will make that optional! 
The major reason for folding it out is performance, this is a "heavy inspector" and drawing all the steps inspectors 100 times per second can really impact the animations. 

But I will make optional :)

**Comment by timbo-tj** [comment]
Ok Thanks! And that's fair enough! 

I looked at the code and it seems like it's supposed to re-expand the steps panel when you press stop.  So I played around with it a little bit. Here is what I discovered:

I tried it out, and it seems a little inconsistent for me. (ie if I play the animation multiple times (press Play twice)) it 'forgets' the fact that it was expanded. So when I press stop, it doesn't re-expand!. ie: 
- `expanded = true, wasExpanded = false`
- Press play 
- `expanded = false, wasExpanded = true`
- Press play again to watch the sequence again
- `expanded = false, wasExpanded = false`
- Press stop to make changes
- Steps panel does not re-expand! Whoops!

And as part of my workflow I am tweaking some prefabs in the prefab stage while the game is running. In this scenario, the Preview panel does not have a Stop button (I guess because game is running!), so there is no way to trigger the re-expand any way!

**Comment by brunomikoski** [comment]
Thanks for the report! I will investigate the workflow you mentioned, but for v0.5.0, you can disable it on the settings:
![image](https://user-images.githubusercontent.com/600419/191552151-6a5a1c38-710c-4afe-b082-7209ba8632a5.png)

https://github.com/brunomikoski/Animation-Sequencer/releases/tag/v0.5.0

**Comment by timbo-tj** [comment]
Oh wow nice stuff! Thanks 👍

**Comment by brunomikoski** [comment]
I fixed the workflow you mentioned, and should be available on the next minor.
