### ISSUE TITLE
serializedObject is 'null' during the last EditorUpdate before OnDisable

### ISSUE THREAD

**Issue by timbo-tj** [brunomikoski/Animation-Sequencer#58]
It seems like there is one additional EditorUpdate prior to OnDisable being called where the serializedObject is 'null' (Not actually null - but it doesn't point to any Unity Object)

Reproduce:

1. Open prefab up in prefab stage. 
2. Select game object which has the `AnimationSequencerControler` component. Needs to be visible in inspector.
3. Close prefab stage
4. Observe Null Reference. `progressSP` is null, was unable to `FindProperty` on the `serializedObject`. Debugging further shows that `serializedObject` has no context/does not point to any targets. I am not sure what is the best/correct way to 'catch' this case. 

Unrelated:
Do you know of any good resources for developing packages locally? I have forked `Animation-Sequencer` and was planning to make some contributions where I could, but I've never developed packages locally. I am not sure what the best workflow is. (How to make changes to the package, test in a dummy (or actual) project in editor, iterate, etc)

Cheers

**Comment by brunomikoski** [comment]
I will take a look into it! 

So for this workflow what I recommend is, fork my repository. 
And clone it as a submodule of your project inside the `Project/Packages` folder.
So you can normally develop and update stuff into your fork, and also create pull requests upstream to my repo! <3 

Any contribution is welcome!
