### ISSUE TITLE
Scripts are not recognized in WebGL, animation sequencer >=0.3.9 and dotween 1.2.705

### ISSUE THREAD

**Issue by mnicolas94** [brunomikoski/Animation-Sequencer#59]
I have a project with DOTween 1.2.705 and Animation Sequencer 0.5.1. Today i changed to WebGL target platform and a lot of errors appear like:
> Assets\Scripts\View\EnemyView.cs(20,34): error CS0246: The type or namespace name 'AnimationSequencerController' could not be found (are you missing a using directive or an assembly reference?)

When I downgrade Animation Sequencer to 0.3.8, the errors go away. Versions >= 0.3.9 still throw errors.

I have another project with Animation Sequencer 0.4.0 and dotween 1.2.690 and errors are not thrown when targeting webgl.

Since Animation Sequencer 0.3.9 introduces the #if DOTWEEN_ENABLED I suspect that is an error with new versions of DOTween not enabling this directive when targeting webgl.

I've not opened this issue in the dotween repo because im not sure of this. So i need confirmation.

**Comment by brunomikoski** [comment]
This looks like the issue that is missing the setup of DOTween might not be completed.

Are you sure you are using the DOTween version from their website and not the ones from OpenUPM? Also could you check if you can see the asmdef files for DOTween inside your project?

**Comment by mnicolas94** [comment]
I installed dotween from the package manager, from my Asset Store's assets. Dotween and animation sequencer work fine if the target platform is Standalone, the problem only occurs when I switch to WebGL. The dotween's asmdef file is inside the project and is succesfully referenced in my own asmdef.

By the way, my project is open-sourced here https://github.com/mnicolas94/ce-fizz-buzz, if you download the **dev** branch and upgrade animation sequencer to >=0.3.9 you should get the errors. I'm currently using animation sequencer 0.3.8 as a workaround.

**Comment by brunomikoski** [comment]
> I installed dotween from the package manager, from my Asset Store's assets. Dotween and animation sequencer work fine if the target platform is Standalone, the problem only occurs when I switch to WebGL. The dotween's asmdef file is inside the project and is succesfully referenced in my own asmdef.
> 
> By the way, my project is open-sourced here https://github.com/mnicolas94/ce-fizz-buzz, if you download the **dev** branch and upgrade animation sequencer to >=0.3.9 you should get the errors. I'm currently using animation sequencer 0.3.8 as a workaround.


Just download and test it a bit, looks like the execution order of my `AnimationSequencerSetupHelper` its getting screwed up by WebGL for some reason, I will have to investigate further to find a proper solution for this, sorry :(.


But you can easily fix this manually for now if you want to use the newer version, just add the `DOTWEEN_ENABLED` on your Scripting Defining Symbols:
![image](https://user-images.githubusercontent.com/600419/197625425-664b4c54-52f2-4a8a-bd69-451dd54a1e56.png)


Should fix your issue for now until I figure out wtf is going on 😂

**Comment by mnicolas94** [comment]
Great thanks!
