### ISSUE TITLE
Unity 2022.2 target object reference bug

### ISSUE THREAD

**Issue by memento3525** [brunomikoski/Animation-Sequencer#61]
https://user-images.githubusercontent.com/14943342/209103836-73586fe2-5e3d-4ef1-ade8-feeea3c56713.mp4

**Top: Normal (unity 2022.1.18f1)
Bottom: Bug (unity 2022.2.1f1)**
Bug point: in 42 seconds

Hello. Thank you for your inspirational plug-in.

However, as the Unity version has been changed to 2022.2, there seems to be a problem with the reference when making Prefab.
It is not clear whether the behavior of the [SerializeReference] has changed or is a bug.

Test version: **Animation-Sequencer-0.5.1**

Tested Normal Operation Version: **2022.1.18f1**
Bugged version: **2022.2.1f1**

Reproduction method
- Create two or three or more Tweens in the sequencer.
- Make Prefab of this object.
- The reference gets tangled at that moment.
(The object's reference points to 'Asset' instead of an instance of the prefab. Animation does not work because it is not an instantiated object.)

It will be solved by downgrading to 2022.1.

**Comment by brunomikoski** [comment]
I will investigate further, but since 2022 its not LTS yet, I don't think I will be able to support it for now.
