### ISSUE TITLE
DisallowMultipleComponent

### ISSUE THREAD

**Issue by guillempd** [brunomikoski/Animation-Sequencer#71]
Hey, first of all, let me tell yout that this is a great tool, very easy to setup and get it working!

I see that the AnimationSequenceController component has [DisallowMultipleComponent]. Would it be possible to remove this? The use case I am trying to achieve is a popup that has different entry and exit transitions, so I would like to add two different AnimationSequenceController components, one for each transition.

I can of course work around this by adding an empty parent to the popup and add the additional AnimationSequenceController to that parent, but it is not ideal, since I would need to do this for each extra AnimationSequenceController.

I understand that multiple AnimationSequenceController playing at the same time would be problematic, but if only one of them is active there should be no problem.

**Comment by brunomikoski** [comment]
Yeah at the moment would not be feasible, mostly because of the editor preview part, I had to do a lot of direct calls to the component and having another one would make things a bit harder. I might be possible with some refactoring, but right now its not possible
